// Generated by Wrangler on Sun Jul 14 2024 21:28:09 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	STRIPE_SECRET_KEY: "sk_test_51NKMzyDcBJMeFPdgrE2l5a4x5HnSJmNFzStwvS4mI4lFWBli5r5MmF95yOHDoJiLAcbVDOvQWAPvzbilJFatsXvt002O4Eofbb";
}
