name = "shortify-stripe-server"
main = "src/server.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
STRIPE_SECRET_KEY = "sk_test_51NKMzyDcBJMeFPdgrE2l5a4x5HnSJmNFzStwvS4mI4lFWBli5r5MmF95yOHDoJiLAcbVDOvQWAPvzbilJFatsXvt002O4Eofbb"